version: '3'

services:
  php:
    container_name: "php"
    build: ./docker/php
    volumes:
    - ./src/laravel:/var/www
    depends_on:
    - mysql

  nginx:
    image: nginx
    container_name: "nginx"
    ports:
    - "80:80"
    volumes:
    - ./src/laravel:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  mysql:
    image: mysql
    container_name: "db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
    - "3306:3306"
    volumes:
    - mydb:/var/lib/mysql

volumes:
  mydb:
